#ifndef _EDGE_DEFINES_H_
#define  _EDGE_DEFINES_H_

#define OCALL_PRINT_BUFFER 1
#define OCALL_PRINT_VALUE 2
#define OCALL_PRIME_CACHE 3
#define OCALL_PROBE_CACHE 4
// #define OCALL_PRIME_ICACHE 5
// #define OCALL_PROBE_ICACHE 6

#endif /* _EDGE_DEFINES_H_ */
